### PR TITLE
Wagtail 4.0 - 5.1

### PR DESCRIPTION
**Pull request by katdom13**
[Wagtail 5.1 release notes](https://docs.wagtail.org/en/stable/releases/5.1.html#upgrade-considerations-changes-affecting-all-projects)

### CODE REVIEW

**Comment by ArnarTumi** [comment]
I tried this branch today as part of an upgrade to wagtail 5, and I am always getting a duplicate devices screen. By that I mean I get the QR code form twice, it seems to be that some javascript is injecting it at the bottom of the dom, since it is not there when I view the source. This also means that I am unable to create a new otp. Are you seeing anything like this?

**Comment by davisnando** [comment]
@ArnarTumi Yes i'm getting the same issue.

**Comment by nickmoreton** [comment]
@davisnando @ArnarTumi Can you try this now, it works for me locally using the sandbox. Thanks

**Comment by davisnando** [comment]
@nickmoreton Seems to work now!

**Pull request merged**
