### PR TITLE
Prevent NoReverseMatch for URLs with required parameters

### PR DESCRIPTION
**Pull request by PeterDekkers**
Resolves https://github.com/labd/wagtail-2fa/issues/51

See the above-linked issue for details.

### CODE REVIEW

**Comment by nnist** [comment]
Hi, thanks for your contribution!

It looks like this no longer uses the `WAGTAIL_MOUNT_PATH` setting which was introduced in #10. I'm afraid that might break some things. Would it be difficult to re-implement this with your current solution?

Other than that, I didn't run into any issues during local testing. I haven't had the time to test it in a larger project yet, hopefully I'll have time to do that in the coming days.

**Comment by editkid** [comment]
Ah yes, good point. I wonder if that setting is even required when using `resolve` 🤔 

Will do some research. Thank you!

**Comment by editkid** [comment]
P.S.: I'd be happy to update unit tests to reflect the middleware changes, provided you're happy with them.

**Comment by PeterDekkers** [comment]
Hello @mikedingjan, @MichielBijland and @nnist. Anything I can do to help get this reviewed? Many thanks!

**Comment by MichielBijland** [comment]
@PeterDekkers I'll plan some time this week

**Comment by PeterDekkers** [comment]
Thanks @MichielBijland. At this stage this PR probably just needs a review of the approach. And, if the approach is deemed valid, a decision on whether or not `WAGTAIL_MOUNT_PATH` is still required at all (I think not).

If `WAGTAIL_MOUNT_PATH` is no longer needed then this PR probably needs to be expanded to remove this setting, update documentation and unit tests. I'm happy to do that and collaborate generally on this.

**Comment by nnist** [comment]
@PeterDekkers I think you're right, we no longer need the  `WAGTAIL_MOUNT_PATH` setting when using your approach.

Considering this PR has been inactive for a while now (sorry!), are you still interested in updating the relevant documentation and unittests for this change, so we can merge this?

**Comment by PeterDekkers** [comment]
@nnist sure thing, I'll update the PR, thanks.

**Comment by nnist** [comment]
Looks good, thank you!

**Pull request merged**
